spring:
  application:
    name: MeiziTu
#  zipkin:
#    baseUrl: http://localhost:9411/zipkin/
  datasource:
    max-idle: 10000
    password: root
    validationQuery: SELECT 1
    testOnBorrow: true
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    max-active: 1000
    driverClassName: com.mysql.jdbc.Driver
#    driverClassName: com.mysql.cj.jdbc.Driver
    max-wait: 18000
    url: jdbc:mysql://127.0.0.1:3306/images?autoreconnect=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root

# redis配置
  redis:
    database: 0
#    host: 119.29.62.179
    host: 127.0.0.1
    port: 6379
    password: redis

    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接超时时间（毫秒）
    timeout: 12000ms



  # 热部署默认为true
  devtools:
    restart:
      enabled: false
server:
  port: 8888
#远程调用要账号密码
#security:
#  basic:
#    enabled: false
#management:
#  security:
#    enabled: false
#  user:
#    password: root
#    name: root
#Zipkin-export: true
#
#flyway:
#  password: root
#  schemas: cbank
#  sql-migration-prefix: V
#  locations: db/migration
#  encoding: UTF-8
#  user: root
#  enabled: false
#  url: jdbc:mysql://localhost:3306/mysql
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false


#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#flyway:
#  enabled: false


# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yudianxx.springBootDemo.mapper.**
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
  #      table-underline: false
  configuration:
    map-underscore-to-camel-case: true
    # mybatis开启二级缓存标志
    cache-enabled: false


logging:
  config: classpath:logback-spring.xml
  level:
    com.yudianxx.springBootDemo: info


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




#meizitu:
#  needInitCache: 0